services:
  weather:
    baseUrl: http://localhost:8080/
  scheduler-sevice:
    baseUrl: http://localhost:8081/
  resources-sevice:
    baseUrl: http://localhost:8083/

#       todo - is this one needed?