server:
  port: 8082
  address: 0.0.0.0

services:
  weather:
    baseUrl: http://localhost:8080/
  scheduler-sevice:
    baseUrl: http://localhost:8081/

sessions:
  monday:
    am:
      water:
        squad:
        levels:
      erg:
        squad:
        levels:
    pm:
      water:
        squad: womens
        levels:
  tuesday:
    am:
      water:
        squad: mens, womens
        levels: intermediate, senior
      erg:
        squad:
        levels:
    pm:
      water:
        squad: womens
        levels: novice, intermediate, senior
      erg:
        squad: mens
        levels: novice, intermediate, senior
  wednesday:
    am:
      water:
        squad:
        levels:
      erg:
        squad: mens, womens
        levels: novice, intermediate, senior
    pm:
      water:
        squad: mens
        levels: novice, intermediate, senior
      erg:
        squad: womens
        levels: novice, intermediate, senior
  thursday:
    am:
      water:
        squad: mens, womens
        levels: intermediate, senior
      erg:
        squad:
        levels:
    pm:
      water:
        squad: development
        levels: development
      erg:
        squad: mens, womens
        levels: novice, intermediate, senior
  friday:
    am:
      water:
        squad:
        levels:
      erg:
        squad:
        levels:
    pm:
      water:
        squad: mens
        levels: novice, intermediate, senior
      erg:
        squad:
        levels:
  saturday:
    am:
      water:
        squad: mens, womens
        levels: novice, intermediate, senior
      erg:
        squad:
        levels:
    pm:
      water:
        squad:
        levels:
      erg:
        squad:
        levels:
  sunday:
    am:
      water:
        squad: development, mens, womens
        levels: development, novice, intermediate, senior
      erg:
        squad:
        levels:
    pm:
      water:
        squad:
        levels:
      erg:
        squad:
        levels: